FROM node:alpine
#RUN npm install -g cnpm --registry=https://registry.npm.taobao.org && cnpm install -g @angular/cli@6.2.4
RUN npm config set registry "https://registry.npm.taobao.org"
RUN npm install -g @angular/cli